version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    image: coin_server
    container_name: coin_server
    ports:
      - 50000:50000
      - 2345:2345
    volumes:
      - ./server:/server
    environment:
      - GO_ENV=dev
      - DOCKER_WORKDIR=/server
      - CGO_CFLAGS=-D_LARGEFILE64_SOURCE
      - TZ=Asia/Tokyo

  client:
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    image: coin_client
    container_name: coin_client
    ports:
      - 30000:30000
      - 60060:60060
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - TZ=Asia/Tokyo

volumes:
  node_modules:
