version: "3"
services:
  go:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: coin_go
    container_name: coin_go
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - ./:/src
    environment:
      GO_ENV: dev